#docker-composeのバージョンを指定
version: "3.8"

volumes:
  db-volume:

#コンテナ詳細
services:
  nginx_server:
    image: nginx:1.18
    container_name: nginx-server
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-app:/var/www/html/laravel-app

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "9000:9000"
    volumes:
      - ./laravel-app:/var/www/html/laravel-app

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel-local
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - db-volume:/var/lib/mysql
